# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FeedSettings.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDateTimeEdit, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QSpinBox, QSplitter, QTimeEdit, QWidget)

class UIFeedSettings(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(800, 602)
        Form.setLocale(QLocale(QLocale.Russian, QLocale.Russia))
        self.button_next = QPushButton(Form)
        self.button_next.setObjectName(u"button_next")
        self.button_next.setGeometry(QRect(390, 480, 281, 101))
        self.splitter_search_settings = QSplitter(Form)
        self.splitter_search_settings.setObjectName(u"splitter_search_settings")
        self.splitter_search_settings.setGeometry(QRect(310, 70, 145, 76))
        self.splitter_search_settings.setOrientation(Qt.Orientation.Vertical)
        self.label_6 = QLabel(self.splitter_search_settings)
        self.label_6.setObjectName(u"label_6")
        self.splitter_search_settings.addWidget(self.label_6)
        self.splitter_5 = QSplitter(self.splitter_search_settings)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Orientation.Vertical)
        self.checkBox_3 = QCheckBox(self.splitter_5)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.splitter_5.addWidget(self.checkBox_3)
        self.checkBox_4 = QCheckBox(self.splitter_5)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.splitter_5.addWidget(self.checkBox_4)
        self.checkBox_5 = QCheckBox(self.splitter_5)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.splitter_5.addWidget(self.checkBox_5)
        self.splitter_search_settings.addWidget(self.splitter_5)
        self.splitter_AI = QSplitter(Form)
        self.splitter_AI.setObjectName(u"splitter_AI")
        self.splitter_AI.setGeometry(QRect(30, 230, 144, 56))
        self.splitter_AI.setOrientation(Qt.Orientation.Vertical)
        self.label_5 = QLabel(self.splitter_AI)
        self.label_5.setObjectName(u"label_5")
        self.splitter_AI.addWidget(self.label_5)
        self.splitter_3 = QSplitter(self.splitter_AI)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Vertical)
        self.checkBox_OpenCV = QCheckBox(self.splitter_3)
        self.checkBox_OpenCV.setObjectName(u"checkBox_OpenCV")
        self.splitter_3.addWidget(self.checkBox_OpenCV)
        self.checkBox_face_rec = QCheckBox(self.splitter_3)
        self.checkBox_face_rec.setObjectName(u"checkBox_face_rec")
        self.splitter_3.addWidget(self.checkBox_face_rec)
        self.splitter_AI.addWidget(self.splitter_3)
        self.spliter_paths = QSplitter(Form)
        self.spliter_paths.setObjectName(u"spliter_paths")
        self.spliter_paths.setGeometry(QRect(20, 370, 481, 49))
        self.spliter_paths.setOrientation(Qt.Orientation.Vertical)
        self.splitter_7 = QSplitter(self.spliter_paths)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.label_8 = QLabel(self.splitter_7)
        self.label_8.setObjectName(u"label_8")
        self.splitter_7.addWidget(self.label_8)
        self.lineEdit_buff_path = QLineEdit(self.splitter_7)
        self.lineEdit_buff_path.setObjectName(u"lineEdit_buff_path")
        self.splitter_7.addWidget(self.lineEdit_buff_path)
        self.spliter_paths.addWidget(self.splitter_7)
        self.splitter_9 = QSplitter(self.spliter_paths)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setOrientation(Qt.Orientation.Horizontal)
        self.label_9 = QLabel(self.splitter_9)
        self.label_9.setObjectName(u"label_9")
        self.splitter_9.addWidget(self.label_9)
        self.lineEdit_save_path = QLineEdit(self.splitter_9)
        self.lineEdit_save_path.setObjectName(u"lineEdit_save_path")
        self.splitter_9.addWidget(self.lineEdit_save_path)
        self.spliter_paths.addWidget(self.splitter_9)
        self.splitter_account = QSplitter(Form)
        self.splitter_account.setObjectName(u"splitter_account")
        self.splitter_account.setGeometry(QRect(20, 80, 211, 121))
        self.splitter_account.setOrientation(Qt.Orientation.Vertical)
        self.label_3 = QLabel(self.splitter_account)
        self.label_3.setObjectName(u"label_3")
        self.splitter_account.addWidget(self.label_3)
        self.splitter = QSplitter(self.splitter_account)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.label = QLabel(self.splitter)
        self.label.setObjectName(u"label")
        self.splitter.addWidget(self.label)
        self.lineEdit_login = QLineEdit(self.splitter)
        self.lineEdit_login.setObjectName(u"lineEdit_login")
        self.splitter.addWidget(self.lineEdit_login)
        self.splitter_account.addWidget(self.splitter)
        self.splitter_2 = QSplitter(self.splitter_account)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.splitter_2)
        self.label_2.setObjectName(u"label_2")
        self.splitter_2.addWidget(self.label_2)
        self.lineEdit_password = QLineEdit(self.splitter_2)
        self.lineEdit_password.setObjectName(u"lineEdit_password")
        self.splitter_2.addWidget(self.lineEdit_password)
        self.splitter_account.addWidget(self.splitter_2)
        self.label_login_error = QLabel(self.splitter_account)
        self.label_login_error.setObjectName(u"label_login_error")
        self.splitter_account.addWidget(self.label_login_error)
        self.button_login_test = QPushButton(self.splitter_account)
        self.button_login_test.setObjectName(u"button_login_test")
        self.splitter_account.addWidget(self.button_login_test)
        self.splitter_limit = QSplitter(Form)
        self.splitter_limit.setObjectName(u"splitter_limit")
        self.splitter_limit.setGeometry(QRect(311, 171, 311, 141))
        self.splitter_limit.setOrientation(Qt.Orientation.Vertical)
        self.label_7 = QLabel(self.splitter_limit)
        self.label_7.setObjectName(u"label_7")
        self.splitter_limit.addWidget(self.label_7)
        self.splitter_4 = QSplitter(self.splitter_limit)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Orientation.Vertical)
        self.splitter_8 = QSplitter(self.splitter_4)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Orientation.Horizontal)
        self.radio_no_limit = QRadioButton(self.splitter_8)
        self.radio_no_limit.setObjectName(u"radio_no_limit")
        self.splitter_8.addWidget(self.radio_no_limit)
        self.splitter_4.addWidget(self.splitter_8)
        self.splitter_14 = QSplitter(self.splitter_4)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setOrientation(Qt.Orientation.Horizontal)
        self.radio_time_limit = QRadioButton(self.splitter_14)
        self.radio_time_limit.setObjectName(u"radio_time_limit")
        self.splitter_14.addWidget(self.radio_time_limit)
        self.timeEdit_time_limit = QTimeEdit(self.splitter_14)
        self.timeEdit_time_limit.setObjectName(u"timeEdit_time_limit")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_time_limit.sizePolicy().hasHeightForWidth())
        self.timeEdit_time_limit.setSizePolicy(sizePolicy)
        self.timeEdit_time_limit.setMaximumSize(QSize(70, 16777215))
        self.timeEdit_time_limit.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.timeEdit_time_limit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.timeEdit_time_limit.setKeyboardTracking(False)
        self.timeEdit_time_limit.setCurrentSection(QDateTimeEdit.Section.HourSection)
        self.timeEdit_time_limit.setDisplayFormat(u"HH:mm:ss")
        self.splitter_14.addWidget(self.timeEdit_time_limit)
        self.splitter_4.addWidget(self.splitter_14)
        self.splitter_13 = QSplitter(self.splitter_4)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Orientation.Horizontal)
        self.radio_add_limit = QRadioButton(self.splitter_13)
        self.radio_add_limit.setObjectName(u"radio_add_limit")
        self.splitter_13.addWidget(self.radio_add_limit)
        self.spinBox_add_limit = QSpinBox(self.splitter_13)
        self.spinBox_add_limit.setObjectName(u"spinBox_add_limit")
        self.spinBox_add_limit.setMaximumSize(QSize(70, 16777215))
        self.splitter_13.addWidget(self.spinBox_add_limit)
        self.splitter_4.addWidget(self.splitter_13)
        self.splitter_12 = QSplitter(self.splitter_4)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Orientation.Horizontal)
        self.radio_check_limit = QRadioButton(self.splitter_12)
        self.radio_check_limit.setObjectName(u"radio_check_limit")
        self.splitter_12.addWidget(self.radio_check_limit)
        self.spinBox_check_limit = QSpinBox(self.splitter_12)
        self.spinBox_check_limit.setObjectName(u"spinBox_check_limit")
        self.spinBox_check_limit.setMaximumSize(QSize(70, 16777215))
        self.splitter_12.addWidget(self.spinBox_check_limit)
        self.splitter_4.addWidget(self.splitter_12)
        self.splitter_limit.addWidget(self.splitter_4)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.button_next.setText(QCoreApplication.translate("Form", u"PushButton", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u043f\u043e\u0438\u0441\u043a\u0430", None))
        self.checkBox_3.setText(QCoreApplication.translate("Form", u"\u041f\u043e\u0438\u0441\u043a \u043b\u044e\u0434\u0435\u0439 \u0432 \u043e\u0447\u043a\u0430\u0445", None))
        self.checkBox_4.setText(QCoreApplication.translate("Form", u"\u041f\u043e\u0438\u0441\u043a \u043b\u044e\u0434\u0435\u0439 \u0432 \u0448\u0430\u043f\u043a\u0435", None))
        self.checkBox_5.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u043c\u044b\u0435 \u043d\u0435\u0439\u0440\u043e\u0441\u0435\u0442\u0438", None))
        self.checkBox_OpenCV.setText(QCoreApplication.translate("Form", u"OpenCV", None))
        self.checkBox_face_rec.setText(QCoreApplication.translate("Form", u"Face Recognition (dlib)", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u041f\u0443\u0442\u044c \u0434\u043b\u044f \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u044b\u0445 \u0434\u0430\u043d\u043d\u044b\u0445:", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u041f\u0443\u0442\u044c \u0434\u043b\u044f \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0434\u0430\u0442\u0430\u0441\u0435\u0442\u0430:", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u041b\u043e\u0433\u0438\u043d:", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u041f\u0430\u0440\u043e\u043b\u044c:", None))
        self.label_login_error.setText("")
        self.button_login_test.setText(QCoreApplication.translate("Form", u"\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u0423\u0441\u043b\u043e\u0432\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u043f\u043e\u0438\u0441\u043a\u0430", None))
        self.radio_no_limit.setText(QCoreApplication.translate("Form", u"\u0414\u043e \u0440\u0443\u0447\u043d\u043e\u0439 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438", None))
        self.radio_time_limit.setText(QCoreApplication.translate("Form", u"\u041f\u043e \u0432\u0440\u0435\u043c\u0435\u043d\u0438", None))
        self.radio_add_limit.setText(QCoreApplication.translate("Form", u"\u041f\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0443 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043d\u044b\u0445 \u0432 \u0411\u0414 \u0432\u0438\u0434\u0435\u043e", None))
        self.radio_check_limit.setText(QCoreApplication.translate("Form", u"\u041f\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0443 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043d\u044b\u0445 \u0432\u0438\u0434\u0435\u043e", None))
    # retranslateUi

